### ISSUE TITLE
ft_putstr_non_printable cant print the Null char.

### ISSUE THREAD

**Issue by Xopper** [jraleman/42_Piscine-C#3]
the function ft_putstr_non_printable cant print the null char so there is a condition will not ever be true.
the condition is in the if statement {str[i] >= 0} should be {str[i] > 0} because in while loop you set 
while (str[i]) that mean str[i] != 0 || str[i] != NULL.
cordially.

**Comment by jraleman** [comment]
Good catch! Feel free to make a PR :)

**Comment by Xopper** [comment]
Thanks
